title: Luu Nhu Hoa
logo: ./hoaln.JPG
description: Embedded Software Engineer.
theme: jekyll-theme-minimal
Author's home: "https://www.strava.com/athletes/5191418"
social-network-links:
  rss: false
  email: "luunhuhoa@gmail.com"  
  linkedin: https://www.linkedin.com/in/hoa-luu-06aa7430/
share-links-active:
 linkedin: true
