title: Luu Nhu Hoa
logo: ./hoaln.png
description: Embedded Software Engineer.
theme: jekyll-theme-minimal
Author's home: "https://www.strava.com/athletes/5191418"
social-network-links:
  rss: false
  email: "luunhuhoa@gmail.com"  
  linkedin: hoa-luu-06aa7430  
